# Generated by Django 3.2.7 on 2021-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='nameuser',
            field=models.CharField(default=123, max_length=60, unique=True, verbose_name='Nome usuario'),
            preserve_default=False,
        ),
    ]
