# Generated by Django 3.2.7 on 2021-11-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_customusuario_nameuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='nameuser',
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='username',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nome usuario'),
        ),
    ]
