# Generated by Django 3.2.7 on 2021-11-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_auto_20211104_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato_empresa',
            name='Empresa',
            field=models.CharField(default='Empresa Teste 07/11/2021', max_length=250, verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
